language: 
  -node_js
  
services:
  - docker

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed eperuza/udagram-api-feed:v2
  - docker tag udagram-api-user eperuza/udagram-api-user:v2
  - docker tag udagram-frontend:local eperuza/udagram-frontend:v3
  - docker tag reverseproxy eperuza/udagram-reverseproxy:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_USERNAME"/udagram-api-feed:v2
  - docker push "$DOCKER_USERNAME"/udagram-api-user:v2
  - docker push "$DOCKER_USERNAME"/udagram-frontend:v3
  - docker push "$DOCKER_USERNAME"/udagram-reverseproxy:v2
