services:
  - docker

script:
  - docker-compose -f docker-compose-build.yaml build
  - docker tag udagram-api-feed eperuza/udagram-api-feed:v1
  - docker tag udagram-api-user eperuza/udagram-api-user:v1
  - docker tag udagram-frontend eperuza/udagram-frontend:v1
  - docker tag udagram-reverseproxy eperuza/udagram-reverseproxy:v1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push eperuza/udagram-api-feed:v1
  - docker push eperuza/udagram-api-user
  - docker push eperuza/udagram-frontend
  - docker push eperuza/udagram-reverseproxy